import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <em>r3f-spaceship!</em> 🚀
        </h1>

        <p className={styles.description}>
          Follow the links below for a step-by-step guide to create the 3D 🚀
          above
        </p>

        <div className={styles.grid}>
          <a href="/01-3d-concepts" className={styles.card}>
            <h2>3D programming concepts &rarr;</h2>
            <p>Basics.</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
